In [1]:
from sklearn import svm,datasets
iris=datasets.load_iris()

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [6]:
df['flower']=iris.target

In [8]:
df['flower']=df['flower'].apply(lambda x:iris.target_names[x])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,
                                              iris.target,
                                              test_size=0.3)

In [15]:
model=svm.SVC(kernel='rbf',C=30,gamma="auto")

In [16]:
model.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [17]:
model.score(x_test,y_test)

0.9777777777777777

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(svm.SVC(kernel="linear",C=10,gamma="auto"),
               iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [20]:
cross_val_score(svm.SVC(kernel="rbf",C=10,gamma="auto"),
               iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
cross_val_score(svm.SVC(kernel="rbf",C=20,gamma="auto"),
               iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [23]:
#here you don't need to write this number of times
import numpy as np

In [24]:
kernels=['rbf','linear']
c=[1,10,20]
avg_score={}
for kval in kernels:
    for cval in c:
        cv_score=cross_val_score(svm.SVC(kernel="rbf",C=20,gamma="auto"),
               iris.data,iris.target,cv=5)
        avg_score[kval+'_'+str(cval)]=np.average(cv_score)

In [25]:
avg_score

{'rbf_1': 0.9666666666666668,
 'rbf_10': 0.9666666666666668,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9666666666666668,
 'linear_10': 0.9666666666666668,
 'linear_20': 0.9666666666666668}

In [27]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma="auto"),{
    'C':[1,10,20],
    'kernel':['linear','rbf'],
},cv=5, return_train_score=False)
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [28]:
clf.cv_results_

{'mean_fit_time': array([0.00096798, 0.0008347 , 0.00077868, 0.00078382, 0.00066381,
        0.00073128]),
 'std_fit_time': array([3.17375125e-04, 3.15826784e-05, 1.07055836e-04, 7.20246072e-05,
        1.66487091e-04, 1.47426868e-04]),
 'mean_score_time': array([0.00047655, 0.00046735, 0.0003335 , 0.00043221, 0.00031333,
        0.00036497]),
 'std_score_time': array([1.88026475e-04, 4.27141773e-05, 1.63071337e-05, 4.54336990e-05,
        6.55449750e-05, 4.67043436e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'ker

In [29]:
df=pd.DataFrame(clf.cv_results_)

In [31]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000968      0.000317         0.000477        0.000188       1   
1       0.000835      0.000032         0.000467        0.000043       1   
2       0.000779      0.000107         0.000333        0.000016      10   
3       0.000784      0.000072         0.000432        0.000045      10   
4       0.000664      0.000166         0.000313        0.000066      20   
5       0.000731      0.000147         0.000365        0.000047      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.973333        0.038873                4  
3         0.980000        0.016330                1  
4         0.966667        0.042164                6  
5         0.966667        0.036515                5

In [32]:
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.980000
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.966667

In [33]:
clf.best_score_

0.9800000000000001

In [34]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [36]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma="auto"),{
    'C':[1,10,20],
    'kernel':['linear','rbf']
    },cv=5,return_train_score=False,n_iter=2)

In [38]:
rs.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']})

In [42]:
f=pd.DataFrame(rs.cv_results_)[["param_C","param_kernel",
                                "mean_test_score"]]

In [43]:
f

param_C param_kernel  mean_test_score
0      20       linear         0.966667
1      10          rbf         0.980000

In [44]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [45]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }  
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [46]:
scores=[]
for model_name,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,
                    return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({"model":model_name,
                  'best_score':clf.best_score_,
                  'best_params':clf.best_params_})

In [47]:
scores

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.96,
  'best_params': {'n_estimators': 10}},
 {'model': 'logistic_regression',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}}]